### ISSUE TITLE
Create compelling contribution markdown file

### ISSUE THREAD

**Issue by leonvanbokhorst** [aiaicaramba/press-to-talk#4]
Explain how to engage with the project.

**Comment by coentjo** [comment]
Not clear what is the best way to look at these issues/emails/PR's... The remarks: are they meant for me? Like: 
'Explain how to engage with the project.' -> what do you mean: is it me engaging in the project yu are setting up? Is it you engaging in itsamatch? Or is it meant a journalist engaging in 'learning'? Or still something else?
